#!/bin/bash

LANGUAGE=en_US.UTF-8 git log --pretty=format:'* `%cd` [%h](https://gitlab.informatom.com/3-schweinehunde/encrateia/-/commit/%h) - %d %s' --abbrev-commit --date=format:'%Y-%m-%d %H:%M' > changelog.txt
