name: encrateia
description: Activity tracker data analysis for Android and iOS

version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  jaguar_query_sqflite: ^2.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  jaguar_orm_gen: 2.2.27


flutter:
  uses-material-design: true