name: encrateia
description: Activity tracker data analysis for Android and iOS
publish_to: none
version: 0.6.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  community_charts_flutter: ^1.0.1
  collection: ^1.17.0
  csv: ^5.0.1
  cupertino_icons: ^1.0.4
  datetime_picker_formfield: ^2.0.0
  dio: ^5.1.1
  dio_cookie_manager: ^2.1.4
  fit_parser: ^2.0.0
  # fit_parser:
  #   path: '../fit_parser'
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_markdown: ^0.6.9
  flutter_material_color_picker: ^1.0.5
  flutter_secure_storage: ^8.0.0
  html: ^0.15.0
  http: ^0.13.4
  package_info: ^2.0.2
  path_provider: ^2.0.9
  sqfentity: ^2.2.0+1.pre
  sqfentity_gen: ^2.2.0+2.pre
  sqflite: ^2.0.2
  strava_client: ^2.0.2
  url_launcher: ^6.0.17
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.3.3
  build_verify: ^3.0.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-R.ttf
        - asset: assets/fonts/Ubuntu-RI.ttf
          style: italic

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icons/runner.png
  image_path_ios: assets/icons/runner-nonalpha.png
