name: encrateia
description: Activity tracker data analysis for Android and iOS

version: 0.4.12

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  charts_flutter: ^0.8.1
  collection: ^1.14.13
  csv: ^4.0.3
  cupertino_icons: ^0.1.2
  datetime_picker_formfield: ^1.0.0
  dio: ^3.0.7
  dio_cookie_manager: ^1.0.0
  fit_parser: ^0.2.0
  # fit_parser:
  #   path: '../fit_parser'
  flushbar: 1.10.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2
  flutter_markdown: ^0.4.1
  flutter_material_color_picker: ^1.0.5
  flutter_secure_storage: ^3.3.1+1
  flutter_staggered_grid_view: 0.3.0
  package_info: ^0.4.0+16
  path_provider: ^1.6.7
  sqfentity: ^1.3.5+3
  sqfentity_gen: ^1.3.5+6
  sqflite: ^1.3.0
  strava_flutter: ^1.2.1+54
  url_launcher: ^5.5.0
  uuid: 2.0.4

dev_dependencies:
  build_runner: ^1.10.1
  build_verify: ^1.1.1

flutter:
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-R.ttf
        - asset: assets/fonts/Ubuntu-RI.ttf
          style: italic

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icons/runner.png
  image_path_ios: assets/icons/runner-nonalpha.png
