name: encrateia
description: Activity tracker data analysis for Android and iOS

version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2
  cupertino_icons: ^0.1.2
  strava_flutter: ^1.1.0+40
  sqfentity: ^1.2.3+1
  sqfentity_gen: ^1.2.1+13

  dio: ^3.0.7
  dio_cookie_manager: ^1.0.0
  flutter_secure_storage: ^3.3.1+1
  provider: ^3.2.0
  fit_parser: ^0.1.6

  charts_flutter: ^0.8.1
  uuid: 2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.5
  build_verify: ^1.1.0

flutter:
  uses-material-design: true

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icons/runner.png
