name: encrateia
description: Activity tracker data analysis for Android and iOS
publish_to: none

version: 0.5.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  charts_flutter: ^0.12.0
  collection: ^1.14.13
  csv: ^5.0.1
  cupertino_icons: ^1.0.4
  datetime_picker_formfield: ^2.0.0
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  fit_parser: ^2.0.0
  # fit_parser:
  #   path: '../fit_parser'
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_markdown: ^0.6.9
  flutter_material_color_picker: ^1.0.5
  flutter_secure_storage: ^5.0.2
  html: ^0.15.0
  http: ^0.13.4
  package_info: ^2.0.2
  path_provider: ^2.0.9
  sqfentity: ^2.2.0+1.pre
  sqfentity_gen: ^2.2.0+2.pre
  sqflite: ^2.0.2
  # strava_flutter: ^1.2.1+54
  strava_flutter:
    git:
      url: git://github.com/dreampowder/strava_flutter
      ref: abf9a78cc30680fe31e88d473b1089bf88ae9cf5
  url_launcher: ^6.0.17
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.7
  build_verify: ^3.0.0
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-R.ttf
        - asset: assets/fonts/Ubuntu-RI.ttf
          style: italic

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icons/runner.png
  image_path_ios: assets/icons/runner-nonalpha.png
