name: encrateia
description: Activity tracker data analysis for Android and iOS

version: 0.2.4

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2
  cupertino_icons: ^0.1.2
  strava_flutter: ^1.2.1+54
  sqfentity: 1.2.3+1
  sqfentity_gen: 1.2.3+3

  dio: ^3.0.7
  dio_cookie_manager: ^1.0.0
  flutter_secure_storage: ^3.3.1+1
  provider: ^3.2.0
  fit_parser: ^0.1.8

  charts_flutter: ^0.8.1
  uuid: 2.0.4
  flushbar: 1.9.1
  path_provider: ^1.6.7

  csv: ^4.0.3
  datetime_picker_formfield: ^1.0.0
  flutter_material_color_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.5
  build_verify: ^1.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-R.ttf
        - asset: assets/fonts/Ubuntu-RI.ttf
          style: italic

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icons/runner.png
  image_path_ios: assets/icons/runner-nonalpha.png
